image: "gitpod/workspace-node:latest"

tasks:
  - init: "cd frontend/my-project && npm i"

vscode:
  extensions:
    - "esbenp.prettier-vscode"
    - "NomicFoundation.hardhat-solidity"
    - "ritwickdey.LiveServer"
