/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/14U9RrzOl25
 */
import { Button } from "@/components/ui/button"

export function Button() {
  return (
    <div key="1" className="bg-[#f4f5f7] min-h-screen">
      <nav className="bg-white shadow">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between h-16">
            <div className="flex">
              <div className="flex-shrink-0 flex items-center">
                <img alt="Logo" className="block lg:hidden h-8 w-auto" src="/placeholder.svg" />
                <img alt="Logo" className="hidden lg:block h-8 w-auto" src="/placeholder.svg" />
              </div>
              <div className="hidden sm:ml-6 sm:flex sm:space-x-8">
                <a
                  className="border-indigo-500 text-gray-900 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium"
                  href="#"
                >
                  Dashboard
                </a>
                <a
                  className="text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium"
                  href="#"
                >
                  Markets
                </a>
                <a
                  className="text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium"
                  href="#"
                >
                  Faucet
                </a>
                <a
                  className="text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium"
                  href="#"
                >
                  More
                </a>
              </div>
            </div>
            <div className="flex items-center">
              <div className="flex-shrink-0">
                <Button className="bg-[#627eea] text-white">0x56...d2ac</Button>
              </div>
            </div>
          </div>
        </div>
      </nav>
      <header className="bg-white shadow">
        <div className="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
          <h1 className="text-3xl font-bold text-gray-900">GHO Sepolia Market</h1>
        </div>
      </header>
      <main>
        <div className="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
          <div className="px-4 py-6 sm:px-0">
            <div className="border-4 border-dashed border-gray-200 rounded-lg h-96">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <div className="bg-white overflow-hidden shadow rounded-lg">
                    <div className="px-4 py-5 sm:p-6">
                      <h3 className="text-lg leading-6 font-medium text-gray-900">Your supplies</h3>
                      <div className="mt-2 max-w-xl text-sm text-gray-500">
                        <p>Nothing supplied yet</p>
                      </div>
                      <div className="mt-5">
                        <Button className="bg-[#627eea] text-white">Supply</Button>
                      </div>
                    </div>
                  </div>
                  <div className="mt-5 bg-white overflow-hidden shadow rounded-lg">
                    <div className="px-4 py-5 sm:p-6">
                      <h3 className="text-lg leading-6 font-medium text-gray-900">Assets to supply</h3>
                      <div className="mt-2 max-w-xl text-sm text-gray-500">
                        <p>Show assets with 0 balance</p>
                      </div>
                      <div className="mt-5">
                        <div className="flex items-center justify-between space-x-4">
                          <span className="text-sm font-medium text-gray-900">ETH</span>
                          <span className="text-sm text-gray-500">0.4898289</span>
                          <span className="text-sm text-gray-500">0%</span>
                          <span className="text-sm text-gray-500">Yes</span>
                          <Button className="bg-[#627eea] text-white">Supply</Button>
                          <Button className="text-[#627eea]">Details</Button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div>
                  <div className="bg-white overflow-hidden shadow rounded-lg">
                    <div className="px-4 py-5 sm:p-6">
                      <h3 className="text-lg leading-6 font-medium text-gray-900">Your borrows</h3>
                      <div className="mt-2 max-w-xl text-sm text-gray-500">
                        <p>Nothing borrowed yet</p>
                      </div>
                      <div className="mt-5">
                        <Button className="bg-[#627eea] text-white">Borrow</Button>
                      </div>
                    </div>
                  </div>
                  <div className="mt-5 bg-white overflow-hidden shadow rounded-lg">
                    <div className="px-4 py-5 sm:p-6">
                      <h3 className="text-lg leading-6 font-medium text-gray-900">Assets to borrow</h3>
                      <div className="mt-2 max-w-xl text-sm text-gray-500">
                        <p>To borrow you need to supply any asset to be used as collateral.</p>
                      </div>
                      <div className="mt-5">
                        <div className="flex items-center justify-between">
                          <span className="text-sm font-medium text-gray-900">GHO</span>
                          <span className="text-sm text-gray-500">0</span>
                          <span className="text-sm text-gray-500">2.02%</span>
                          <span className="text-sm text-gray-500">—</span>
                          <Button className="bg-[#627eea] text-white">Borrow</Button>
                          <Button className="bg-[#ffffff] text-[#000000] bg-gray-100">Details</Button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
